### ISSUE TITLE
JSON Input

### ISSUE THREAD

**Issue by sejori** [MaximBuz/custom-cli-tools#1]
Awesome idea Maxim!

Storing the getAll, getByIdThe and mutation endpoints in a JSON file that can be used as an input to your CLI might be very handy. The tool is currently one-time-use at the start of a project but if it could be reused as project requirements change etc then it could be even more useful.

However, this would require some sort of cleanup functionality that can remove previously generated files and regenerate from the provided inputs. But I guess that could be achieved by storing all previously made files somewhere? Maybe I'm over-engineering this (feel free to close this issue if you think so)!

**Comment by MaximBuz** [comment]
I think that would be totally awesome!

In fact I was thinking of maybe parsing a JSON that would be very similar to what Postman expects when importing endpoints. I will totally look into that

**Comment by sejori** [comment]
Great idea - there are lots of standardized JSON schemas out there so I'm sure you'll find one for API endpoints 👍

**Comment by MaximBuz** [comment]
I refactored the code to using a JSON schema now. You can test it out. I have not yet implemented the overwriting and cleanup functionality, as I believe it might be best to create a seperate issue for that.
